PREFIX : <http://semantics.id/ns/example/film#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?film_title
WHERE {
  ?film rdf:type :Film .
  ?film rdfs:label ?film_title .
}
